### ISSUE TITLE
Redact picoCTF 2022 sections until March 29, 2022 when competition is over

### ISSUE THREAD

**Issue by hi-liang** [brootware/staging.github.io#2]
We would greatly appreciate folks refrain from public posting write-ups until the competition is over

**Comment by brootware** [comment]
> We would greatly appreciate folks refrain from public posting write-ups until the competition is over 

Sure @hiliang-cmu . Apologies. Will be redacting them now.

**Comment by brootware** [comment]
The file has been redacted together with commit histories. @hiliang-cmu thank you for spotting this. Closing this issue for now.

**Comment by hi-liang** [comment]
Ty!
